Add comprehensive memory model tests
gpuweb/cts pull request #1330
Opened 2022-04-28 18:03 UTC by reeselevine

Issue: #963 

- Adds remaining memory model tests from https://gpuharbor.ucsc.edu/webgpu-mem-testing/conformance/
- A total of 40 memory model tests are now included. On my Intel Macbook, the tests finish in ~30 seconds.
- A couple minor updates to the setup code are included so that all tests work correctly and fixed parameters can't be accidentally changed
- Parameter sets for coherence/weak memory tests are updated to use values found to be the most effective when doing experiments

@dneto0 @alan-baker @tyler-utah

P.S. I'm not sure if it's unexpected that `package-lock.json` has changes. If this is bad, I can revert it to the current `package-lock.json` on the main branch.
<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

2022-04-28 19:32 UTC, zoddicus reviewed
I have added a review comment about the package-lock.json change, but scanning over the rest of the PR, I don't think I am qualified to approve it in general, since I am not particularly familiar with the memory model and workgroup management in WGSL. Since @dneto0 is away I have added @ben-clayton who hopefully will have enough context to give a proper review.

2022-04-28 19:32 UTC, zoddicus commented on package-lock.json
>        }
I wouldn't expect this needed to be updated unless you are explicitly using functionality from newer packages, so I would probably revert to main unless there is something specific you need to update for.

2022-05-06 14:59 UTC, dneto0 commented
I plan to review this.  It's in my queue.

2022-05-09 20:47 UTC, dneto0 requested changes
Looking really good.
Two requests:
- more consistent naming of the test code snippets.
- add RMW workgroup-storage variants when there are storag-buffer variants.

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +  let r1 = atomicAdd(&test_locations.value[y_1], 0u);
So we have two independent dimensions:    storage vs. workgroup; and  read-read vs read-RMW.
So there should be 4 variants, but there are only 3.

Seems we should also test RMW on the workgroup storage.

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +  let r1 = atomicAdd(&test_locations.value[y_1], 0u);
For consistency with the others, should this be called storageMemoryCorrRMWTestCode ?

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +const cowwRMWTestCode = `
suggest renaming to storageMemoryCowwRMWTestCode

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +const workgroupMemoryCowwTestCode = `
Suggest adding a RMW variant too.

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +const cowrRMWTestCode = `
suggest remaing to storageCowrRMWTestCode

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +const workgroupMemoryCowrTestCode = `
Suggest adding a RMW variant

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +const corw2RMWTestCode = `
similarly, rename

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/coherence.spec.ts
> +const workgroupMemoryCorw2TestCode = `
similarly, add a RMW variant for workgroup memory

2022-05-09 20:47 UTC, dneto0 commented on src/webgpu/shader/execution/memory_model/memory_model_setup.ts
> +  let isStorageClass = false;
FYI.  We renamed "storage class" to "address space", so you can rename this  isStorageAS or something like that.

2022-05-10 19:46 UTC, reeselevine commented
Added more RMW variants! There are actually three "types" of coherence tests: inter-workgroup on storage address space, intra-workgroup on storage as, and intra-workgroup on workgroup as. I've added rmw variants for all three of these, as well as addressed the other minor comments.

2022-05-11 20:38 UTC, dneto0 approved these changes
I understand even better now.
LGTM, and thanks!

2022-05-11 20:39 UTC, merged