Move f32 short values
gpuweb/cts pull request #1754
Opened 2022-08-15 18:35 UTC by zoddicus

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

2022-08-15 18:36 UTC, zoddicus commented
This depends on https://github.com/gpuweb/cts/pull/1748, so the only new code is in https://github.com/gpuweb/cts/pull/1754/commits/e6506c06108239a3842dac49ef3a6a9b49f16721

2022-08-16 19:49 UTC, dj2 approved these changes

2022-08-17 12:42 UTC, ben-clayton requested changes
No PR description, and the PR subject doesn't seem to match the content.

2022-08-17 15:33 UTC, zoddicus commented
This is based off my `dot` implementation, so all of the new code is in patch 59c12e0fe6b28ed32933022831501eb479431c7f

2022-08-17 18:54 UTC, zoddicus commented
PTAL, this is ready for review

2022-08-18 14:18 UTC, zoddicus commented
@ben-clayton can you take another look at this, GitHub is wanting your approval to land, since you requested changes.

2022-08-18 15:33 UTC, ben-clayton approved these changes

2022-08-18 15:33 UTC, ben-clayton commented on src/webgpu/util/math.ts
> + * @returns a ascending sorted array of numbers spread over the entire range of 32-bit floats
nit: shouldn't this be `an` ?

2022-08-18 16:30 UTC, zoddicus commented on src/webgpu/util/math.ts
> + * @returns a ascending sorted array of numbers spread over the entire range of 32-bit floats
Done

2022-08-18 16:50 UTC, merged