Compat: Refactor tests to use @interpolate(flat, either)
gpuweb/cts pull request #3814
Opened 2024-06-25 00:16 UTC by greggman

These tests need `@interpolate(flat, either)` to be able to run on compat mode.

Note that they will all start failing on core if core is missing support for `'either'` sampling.

<hr>

**Requirements for PR author:**

- [X] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [X] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [X] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)
- [X] Test have be tested with compatibility mode validation enabled and behave as expected. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

2024-06-25 17:13 UTC, jrprice requested changes

2024-06-25 21:04 UTC, greggman commented on src/webgpu/shader/validation/shader_io/builtins.spec.ts
> +      t.params.first === 'p1' ? '@builtin(sample_mask)' : '@location(1) @interpolate(perspective)';
thanks for catching that. fixed

2024-06-25 21:04 UTC, greggman commented on src/webgpu/shader/validation/shader_io/locations.spec.ts
> +      attribute: '@location(0) @interpolate(perspective)',
fixed

2024-06-26 13:09 UTC, jrprice approved these changes

2024-06-26 15:46 UTC, merged