Add validation of subgroup_uniformity diagnostic
gpuweb/cts pull request #4066
Opened 2024-11-27 18:12 UTC by alan-baker

Issue: #

<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)
- [ ] Test have be tested with compatibility mode validation enabled and behave as expected. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

2024-11-29 18:35 UTC, dneto0 requested changes

2024-11-29 18:35 UTC, dneto0 commented on src/webgpu/shader/validation/parse/diagnostic.spec.ts
> +      t.selectDeviceOrSkipTestCase('subgroups' as GPUFeatureName);
It's valid to use unknown diagnostics.  I think this should not skip.
(I know testing unrecognized diagnostics is tested below for `warning_unknown_rule`)

2024-11-29 19:16 UTC, jrprice approved these changes

2024-12-03 19:03 UTC, dneto0 approved these changes

2024-12-03 20:03 UTC, merged