shader/execution: Implement quantizeToF16() tests
gpuweb/cts pull request #796
Opened 2021-10-26 13:36 UTC by ben-clayton

<hr>

**Author checklist for test code/plans:**

- [x] All outstanding work is tracked with "TODO" in a test/file description or `.unimplemented()` on a test.
- [x] New helpers, if any, are documented using `/** doc comments */` and can be found via `helper_index.txt`.
- [x] (Optional, sometimes not possible.) Tests pass (or partially pass without unexpected issues) in an implementation. (Add any extra details above.)

**[Reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) for test code/plans:** (Note: feel free to pull in other reviewers at any time for any reason.)

- [ ] The test path is reasonable, the [description](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) "describes the test, succinctly, but in enough detail that a reader can read only the test plans in a file or directory and evaluate the completeness of the test coverage."
- [ ] Tests appear to cover this area completely, except for outstanding TODOs. Validation tests use control cases.
    (This is critical for coverage. Assume anything without a TODO will be forgotten about forever.)
- [ ] Existing (or new) test helpers are used where they would reduce complexity.
- [ ] TypeScript code is readable and understandable (is unobtrusive, has reasonable type-safety/verbosity/dynamicity).

2021-11-02 20:18 UTC, dneto0 requested changes

2021-11-02 20:18 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/quantizeToF16.spec.ts
> +      { input: f32(-32768.0), expected: f32(-32768.0) },
Please add some cases showing fractional numbers in more friendly form:

   1.5
   2.375
   -1.5
   -2.375

2021-11-02 20:18 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/quantizeToF16.spec.ts
> +      { input: f32Bits(0x38802000), expected: f32Bits(0x38802000) }, // the next representable f16 number greater than 1.0
Readability of these cases would benefit from a helper function to compose an f16 bit pattern from sign, exponent, and mantissa bits.  That helper could go in the conversions.ts ?

2021-11-02 20:18 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/quantizeToF16.spec.ts
> +      { input: f32Bits(0xb8802000), expected: f32Bits(0xb8802000) }, // the next representable f16 number less than -1.0
By less, you mean smaller magnitude... because it's negative.

2021-11-02 20:18 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/quantizeToF16.spec.ts
> +      { input: f32Bits(0xb8802001), expected: anyOf(f32Bits(0xb8802000), f32Bits(0x38806000)) }, // slightly larger than the next representable f16 number > 1.0
These result constants are hard to interpret.

2023-05-02 14:21 UTC, zoddicus commented
Superceded by by https://github.com/gpuweb/cts/pull/1828

2023-05-02 14:21 UTC, closed without merging