Implement `inverseSqrt` tests
gpuweb/cts pull request #926
Opened 2022-01-18 20:54 UTC by zoddicus

<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

2022-01-18 20:57 UTC, zoddicus commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +}
All of the range generation code can probably be factored out into a utility file and used by other tests that test a range of programmatically values.

I wanted to get this reviewed before I did that refactoring, and also wasn't sure if I should do that in a separate PR. i.e. land this test PR and then have a follow up that factors out the utility code and update other tests to use it.

2022-01-18 20:57 UTC, zoddicus commented
PTAL

2022-01-18 22:28 UTC, dneto0 requested changes
I have some nitpicks about comments, and a request for a better (more numerically good) lerp function.  I guess the lerp niceness doesn't matter in this case, but it may get reused where it does matter.

2022-01-18 22:28 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +  if (t > 1) {
I'd include the end range too, just for potential tidiness.   

      t >= 1

2022-01-18 22:28 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +  if (t < 0) {
Similarly  `t  <= 0`

2022-01-18 22:28 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +  return min + t * (max - min);
I wonder if this is good numerically.  For example, if max and min are both large magnitude and close to each other, then you get catastrophic cancellation.
(Subtracting to float numbers that agree to k bits means you lose k bits of precision, generally).

My next thought was to suggest:


       (min * (1-t)  + max * t)

Then I googled "numerically stable linear interpolation" and found someone who has thought about this way more deeply. There is a relatively simple solution that has nice properties.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0811r2.html 

Please use the suggested algorithm.

2022-01-18 22:28 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +function unwrapRangeParams(min: Scalar, max: Scalar, steps: Scalar) {
What is the steps parameter? The size of the step between min and max, or the number of steps.

I have to read the body to be sure.

2022-01-18 22:28 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +    lerp(f32_min, f32_max, Math.pow(lerp(0, 1, i / (u32_steps - 1)), 2))
Interesting.  So you square the lerp'd steps, so it's like a up-facing parabola (quadratic) from the origin to (1,1), if I am reading this correctly.
A comment summarizing that would be nice.

2022-01-18 22:28 UTC, dneto0 commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +  .fn(async t => {
This is really nice!

2022-01-19 20:04 UTC, zoddicus commented on src/webgpu/shader/execution/builtin/inversesqrt.spec.ts
> +}
Once this PR lands I will refactor and send out another PR.

2022-01-19 20:05 UTC, zoddicus commented
@dneto0 this is ready for another round of review

2022-01-20 20:55 UTC, dneto0 approved these changes
Looks great!

2022-01-20 21:39 UTC, merged